### ISSUE TITLE
Mark properties as required in Steps

### ISSUE THREAD

**Issue by pawelk9** [takinosaji/TestUnium#1]
It'd helpful to have for example [Required] attribute for properties in Step class

```
public class StepA: BaseStep
    {
        [Required]
        public string PropA{ get; set; }

        public override void Execute()
        {
            // usage that requires PropA
        }
    }
```

If PropA is not set then some exception should be thrown (for example: "PropA should be set for StepA")

**Comment by takinosaji** [comment]
Very nice suggestion. Thanks.

1st variant: We can check if the value of property/field differs from 
it's default value since unassigned fields has default values after creation of the instance.
It means that if you have Int32 field in step and in Do method you set it's value = 0, the framework wont be able to understand whether you assigned value or not. This is simply solved by not enriching the property with Required attribute.

2nd variant: If you need to catch the fact of setting field or property itself we must parse lambda expression. I will look how to realize this.

**Comment by takinosaji** [comment]
Was implemented in TestUnium package v. 1.1.5.
Please feel free to decorate fields and properties of your step class with [RequiredAttribute](https://msdn.microsoft.com/en-us/library/system.componentmodel.dataannotations.requiredattribute%28v=vs.110%29.aspx).
